packages:
  - packages/*
  - apps/*

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  msgpackr-extract: true

catalog:
  '@effect/language-service': 0.86.4
  '@effect/platform-node': 4.0.0-beta.94
  '@types/node': 24.3.0
  effect: 4.0.0-beta.94
  tsx: 4.20.6
  typescript: 5.9.2
